// Generated by https://quicktype.io

export interface Data {
  updated:                number;
  cases:                  number;
  todayCases:             number;
  deaths:                 number;
  todayDeaths:            number;
  recovered:              number;
  todayRecovered:         number;
  active:                 number;
  critical:               number;
  casesPerOneMillion:     number;
  deathsPerOneMillion:    number;
  tests:                  number;
  testsPerOneMillion:     number;
  population:             number;
  continent:              string;
  activePerOneMillion:    number;
  recoveredPerOneMillion: number;
  criticalPerOneMillion:  number;
  continentInfo:          ContinentInfo;
  countries:              string[];
}

export interface ContinentInfo {
  lat:  number;
  long: number;
}

// Generated by https://quicktype.io

export interface CountryData {
  updated:                number;
  country:                string;
  countryInfo:            CountryInfo;
  cases:                  number;
  todayCases:             number;
  deaths:                 number;
  todayDeaths:            number;
  recovered:              number;
  todayRecovered:         number;
  active:                 number;
  critical:               number;
  casesPerOneMillion:     number;
  deathsPerOneMillion:    number;
  tests:                  number;
  testsPerOneMillion:     number;
  population:             number;
  continent:              string;
  oneCasePerPeople:       number;
  oneDeathPerPeople:      number;
  oneTestPerPeople:       number;
  activePerOneMillion:    number;
  recoveredPerOneMillion: number;
  criticalPerOneMillion:  number;
}

export interface CountryInfo {
  _id:  number;
  iso2: string;
  iso3: string;
  lat:  number;
  long: number;
  flag: string;
}
